sudo: required

language: php
php:
- '7.1.9'

branches:
  only:
  - master

# travis runtime environment from here or settings. : https://docs.travis-ci.com/user/environment-variables/
env:
  global:
  - ZIP_FILE="php-$TRAVIS_BUILD_NUMBER-$TRAVIS_COMMIT.zip"

  # travis-ci secure doc : https://docs.travis-ci.com/user/encryption-keys/
  # before install travis , first install ruby & gem
  # $ gem install travis
  # $ travis encrypt SOMEVAR="secretvalue"

  # AWS_ACCESS_KEY_ID_DEV
  - secure: ""
  # AWS_SECRET_ACCESS_KEY_DEV
  - secure: ""
  # AWS_ACCESS_KEY_ID_STG
  - secure: ""
  # AWS_SECRET_ACCESS_KEY_STG
  - secure: ""
  # AWS_ACCESS_KEY_ID_PROD , value : AKI....QMQ
  - secure: "NOl0Dh4sDsJESaWkshBgZORoHg1Gr92OORQDCucxyxnxKDSQcpDsPkgee5UfN0JnNK+Fx7rtxyZges8fnMVqaGMbUZTnALdSvHPeSYLnjqtb0FRfcpNjoDJrGLy6H3OdL0phFBlk4hbTjYuNDWM92CTYWHoUVcPTmCI8Qyvp2oBXlP1VI5HRKk9Y54vSlbjii4SCLSBjz4wZwl6kHhU7dwJjEDET2SjfZZ6RGXjo2AerrK/pOle5ig59dag2fR7/MW50a9dZMHoWEdmNZ2QAdQYZZtkjO9Ssf4LrQjWbhMzoDrGsHDpxca+YgsJZEL9MMAbY3+/kOmRm8Dh1Whr8kWkNjuvQW6J5FBHrLn5+YPeAx4cfu3NKBwZk45vIzORTA6hBpDGhf9NibSPP2B5RFIZoE6UpUo5AhNuVWhA+mFtFN4kZKCekbHqgZgHFyPNjTbc7L8pwOPvw7El5sEx1t5rWj/AkPT8bp7M/+Eaa0Ky/n97WAva8XZ6SJRsofcJe1J8RgEx1+CBWh6+oNsWiZ6rItD1omoxRoSHVqTtjHjpgurWUaUFjXu1DVFUWoJCRtG3yFCH5kTNXymcX9JMdi2iWEjArI9lvzbPQ2PRMdzvADzW06AbR52n/Rh6ZFFFJY1eJ5/OhMyE2kxLNwLQOs3gevbr81zNt4iBPKWmVmBA="
  # AWS_SECRET_ACCESS_KEY_PROD
  - secure: "LVbQxn/Kxm3Mb3pKFvmg7RPydubR8G5jBmZOblD+/G7hzcFuEXd3FIPMDJGTzuSc8xgXGJIRua/7dB/b+RHoG/olLWkk4x0RRiPfXgMo8uiETwuhHWcviE67lcpCz0M57HxiecZE/fv6+5JncdJaVFlJlOjJZFPAL4TSSHVV0K8hE5vMogGc8xp/5EMqSoFSXwXeM75omhKCwqkODASvNgRkaXLjURarzTAuJJLZm+/RXRW1UYR9MLkAnkN1rYyY3gwALycTGmHhiOK0VuQV52DzNTcyHt0NjeI9PXsoFOQOCVm0T80dfXVj7DcTMFeO9yYkFbmLBpudFf3u04i2DOM57omf2Gdr930NuspD0pDRHZprJ/fKZBdh0qHgobxoA1lh9xffTY3PnG4Wi27dFrhX6z+x9WsbQCI/F/fEW4C32nly5k0asc2iIudHJ7ejh6Z91yg+k2c7UZgjlg2QQak876wV0jlnYPtzCHdX1yIC602qDUEHtNEWrswi7KZwzbFlJAvuF8CBix/ROijcGH21OXUU+ZRwAEVj629KqKJKiyjNhSNDo1bIlGAse5umn0AwzTDRy2rq+7+qdiZKFIgRjVkeNYQ1R1hQP3h9OpZC5U6KJjHy8vmnrt0xSyV+x1tmdddXJvQ498xbbFSUXRDE/02iL3nq0KkSZI7sc7s="

  # global variables
  - AWS_ACCESS_KEY_ID=''
  - AWS_SECRET_ACCESS_KEY=''
  - AWS_REGION='ap-northeast-1'
  - CODEDEPLOY_APP_NAME=''
  - CODEDEPLOY_GROUP=''


# notification - https://docs.travis-ci.com/user/notifications
# notifications:
#   email:
#     recipients:
#       - one@example.com
#       - other@example.com
#     on_success: never # default: change
#     on_failure: always # default: always
# integration to slack , setup on slack travis-ci app
notifications:
  email:
    on_failure: always
    on_success: never
  slack:
    rooms:
    - secure: "nvZeorvWzV84hIklTVrKNGMAcZGhBgsBmk3uTtR8xE/StWg5XirabllpOCrnpYDqJ5ccrNF1FpAqMPbcT1T31KsQkp+1IN5q6yuua8uIk2xytSmlMvae6RFsqXTz39Cwul3fjxkvRYPsF/yx2qXkagwk5N3y7lrwvpncnRho3mcOP8ZCoti3a1ZWNMlkGopDGQIP/dy/qiH2qsbKl6JgooC6MqbTw/xERNkbRIg6ZZF8j7U4Kc/s/00fDKIeVD7wYlPOfhcG/JKDf79H4h5KqQsVX+O+oVKtrRdtgWdluGku0JF7gq2vU66YZkK+WoT138VbyGcN3tkKbudwXs5voByy9f4su7DIJu7ghh7OQpKRn3Vnj+2JCaijEGFlUfk4woMA9ZtY9E1hkYNoD503PFBGGuy2cBYysNB9XrO/c0oXEG150jCjt09elELeOKAIOO5z/+8XpZ0G929FSsKmC+FxzZg+U3zPyPVKBufeVcx1NBe4N9r8n0nXUl+Ewy+JAXgMYF9vgyzybNf/hw/HhaL7I07ieUcBENZ/3k9NO/B7axXpMxBMu7O6el7kpU+9WWhuQl6+mLrIMW1cRnkxAdnTYqh2LP3cCBF+LD4XouyN3DJ3QqASczI0P3OmFKbQNc5fudfx2eQZMZ0qCzTRxQA+7uXTyvi2gKP4t5+sCWA="

cache:
  directories:
  - $COMPOSER_CACHE_DIR
  - $HOME/.composer/cache




# build lifecycle - https://docs.travis-ci.com/user/customizing-the-build/
# (OPTIONAL) Install apt addons
# (OPTIONAL) Install cache components
# before_install
# install
# before_script
# script
# (OPTIONAL) before_cache (for cleaning up cache)
# after_success or after_failure
# (OPTIONAL) before_deploy
# (OPTIONAL) deploy
# (OPTIONAL) after_deploy
# after_script

# set -e : when error stop build.
before_install:
- set -e
- echo `date +"%Y-%m-%d %H:%M:%S"`
- echo $TRAVIS_BRANCH
- if [[ $TRAVIS_BRANCH == "dev" ]]; then
    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_DEV;
    AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_DEV;
    S3_BUCKET='';
    CODEDEPLOY_APP='';
    CODEDEPLOY_GROUP='';
  fi
- if [[ $TRAVIS_BRANCH == "staging" ]]; then
    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_STG;
    AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_STG;
    S3_BUCKET='';
    CODEDEPLOY_APP='';
    CODEDEPLOY_GROUP='';
  fi
- if [[ $TRAVIS_BRANCH == "master" ]]; then
    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_PROD;
    AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_PROD;
    S3_BUCKET='demo-yuhsing-465987345257698435';
    CODEDEPLOY_APP='demo-EC2-CodeDeploy';
    CODEDEPLOY_GROUP='ec2';
  fi


# put testing scripts here
script:
- echo 'script step...'

before_deploy:
- cd "$TRAVIS_BUILD_DIR";
  mkdir "$TRAVIS_BUILD_DIR/zip";
  zip -r "$TRAVIS_BUILD_DIR/zip/$ZIP_FILE" *


deploy:
- provider: S3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: $AWS_REGION
  local_dir: $TRAVIS_BUILD_DIR/zip
  bucket: $S3_BUCKET
  skip_cleanup: true
  on:
    all_branches: true

- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: $AWS_REGION
  bucket: $S3_BUCKET
  key: $ZIP_FILE
  bundle_type: zip
  application: $CODEDEPLOY_APP
  deployment_group: $CODEDEPLOY_GROUP
  wait_until_deployed: true
  on:
    all_branches: true
